### ISSUE TITLE
docs: Document adding domain annotation before helm install

### ISSUE THREAD

**Issue by technosophos** [deis/workflow#112]
Right now the current docs suggest running a straight Helm install.

https://github.com/deis/workflow/blob/master/docs/src/installing-deis/installing-the-deis-platform.md

In practice, the Deis router is not ready out of the box. So the current workflow that I have to use is this:

```
$ helm fetch deis/deis
$ vi $(helm home)/workspace/deis/manifest/deis-router-rc.yaml
$ helm install deis
```

In the second step, I have to do something like this:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-router
  namespace: deis
  labels:
    heritage: deis
  annotations:
    deis.io/routerConfig: |
      {
        "domain": "10.245.1.3.xip.io",
        "useProxyProtocol": false
      }
```

Unless there is a better workaround, this seems to be required to get _any_ deis cluster working.

/cc @krancour
