### ISSUE TITLE
Workflow without LBaaS

### ISSUE THREAD

**Issue by cdupont** [deis/workflow#626]
Hi there,
I installed Deis but without LBaaS. Details why are here: https://github.com/Waziup/Platform/issues/32
So my deis-router is configured with `Service type = NodePort`.
I configured an ingress controller though, that allows me to configure an app on a URL such as myapp.mysite.com
http://kubernetes.io/docs/user-guide/ingress/

Currently when I push an app:
```
git push deis master
```
It returns an url that is not valid (says `http://leader-windmill.waziup.io/`).
I have to create an ingress resource myself to route the application:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: leader-windmill
  namespace: leader-windmill
spec:
  rules:
  - host: leader-windmill.waziup.io
    http:
      paths:
      - path: /
         backend:
          serviceName: leader-windmill
          servicePort: 80
```

Is it possible that deis uses my ingress controller automatically?
