### ISSUE TITLE
Using Pod fields as values for environment variables

### ISSUE THREAD

**Issue by gottfrois** [deis/workflow#751]
If the feature already exists, this is more of a question, otherwise it would be really nice to be able to do this.

Kubernetes allows to define ENV variables using pod fields as values:

```
apiVersion: v1
kind: Pod
metadata:
  name: ...
spec:
  containers:
    - name: ...
      image: ...
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
```

Is this possible using `deis config:set` command? If not, what would it take to allow this in futur release of deis?

More information [here](https://kubernetes.io/docs/tasks/configure-pod-container/environment-variable-expose-pod-information/).

**Comment by bacongobbler** [comment]
It is not possible to reference the downward API today with pods. However, you can infer the pod namespace by the application name, which is available in the environment. The pod IP and others are currently unavailable, however we've generally pushed back on that due to concerns of exposing the cluster to the application developer (most multi-tenant systems like Heroku do not give you host information, for example).

Service account information is also unavailable because we don't want application pods talking to the kube api.

If you'd like to take a tackle at this, you probably will want to make a proposal or write documentation that comes up with a couple use cases for this as well as how it'd look in the CLI, then write a PR against that doc.

Hope this helps!

**Comment by gottfrois** [comment]
thanks @bacongobbler for the quick answer. Being able to know POD IP as well as the host the POD is running on might be valuable information in order to force services communication to go through a service mesh running as a DaemonSet on the same host the POD is running.

I'm using [linkerd](https://linkerd.io/) to abstract services communication and the way it is setup is my having all http requests proxy through the linkerd instance running on the same host as the POD.

Here is the k8s POD configuration:

```
env:
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: http_proxy
  value: $(NODE_NAME):4140
```

The `POD_IP` is really just to ensure load balancing is working while testing my setup but the `NODE_NAME` is used to make sure we proxy http requests through the local instance of linkerd.

Hope it helps to understand the usecase better.
Do you see any workaround for the moment?
