### ISSUE TITLE
Experimental Native Ingress not supporting `deis domain`

### ISSUE THREAD

**Issue by mariusmarais** [deis/workflow#816]
Yes, I know the feature is experimental :)

I've been testing the native ingress (per https://github.com/deis/workflow/pull/732) in combination with Traefik and Let's Encrypt.  Thus far it was pretty painless and seems to work well.

The lack of vanity domains does prevent me from giving it a proper test though, since `deis domain:add xxx` effectively does noting in this configuration.

Manually editing the app's ingress to add the correct host spec works as expected, so it seems that the only missing thing is the controller doing this automatically when native ingress is enabled:

```yaml
...
spec:
  rules:
  # Original, deis-created rule
  - host: ui.apps.ss1.k8s.xxx
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
        path: /
  # Manually added rule
  - host: helloworld.k8s.xxx
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
        path: /
```

(FWIW: "Proper test" means giving devs access to this cluster to deploy a few low-risk apps without ops intervening to update hostnames.)
